### ISSUE TITLE
Support LÖVE 11.2

### ISSUE THREAD

**Issue by tobiasvl** [pico-8/picolove#4]
Looks like mostly small changes.

**Comment by MineRobber9000** [comment]
To start, try using [the cindy library](https://github.com/megagrump/cindy) and `cindy.applyPatch()`. See what else needs to be fixed and we can work on that.

**Comment by MineRobber9000** [comment]
Actually, picolove as is [runs fine on 11.2](https://github.com/pico-8/picolove/blob/master/conf.lua#L3). (technically it's for 11.0 but whatever)
